# Generated by Django 5.1.5 on 2025-01-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
