# Generated by Django 5.1.5 on 2025-01-28 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_mobile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_staff_count', models.IntegerField(default=0)),
                ('sales_staff_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_counts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
