# Generated by Django 5.1.5 on 2025-01-28 05:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_updated_at_alter_supplier_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='NP'),
        ),
    ]
